# Generated by Django 4.2.13 on 2024-07-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
    ]
